package com.shoptracker.expense.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * A single money movement. Stored both in the global "Transactions" sheet and,
 * when it is linked to a buyer, mirrored into that buyer's dedicated worksheet.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transaction {

    /** Unique id (UUID string). Generated by the service on create. */
    private String id;

    private LocalDate date;

    /** Optional. Empty / null for pure personal expense or income entries. */
    private String buyerName;

    private TransactionType type;

    private double amount;

    private String description;

    private PaymentMode paymentMode;

    /** Running buyer balance after this transaction (buyer sheet only). */
    private double balanceAfter;
}
